#output port
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_control[0]}]
set_property PACKAGE_PIN L1 [get_ports {LED_control[15]}]
set_property PACKAGE_PIN P1 [get_ports {LED_control[14]}]
set_property PACKAGE_PIN N3 [get_ports {LED_control[13]}]
set_property PACKAGE_PIN P3 [get_ports {LED_control[12]}]
set_property PACKAGE_PIN U3 [get_ports {LED_control[11]}]
set_property PACKAGE_PIN W3 [get_ports {LED_control[10]}]
set_property PACKAGE_PIN V3 [get_ports {LED_control[9]}]
set_property PACKAGE_PIN V13 [get_ports {LED_control[8]}]
set_property PACKAGE_PIN V14 [get_ports {LED_control[7]}]
set_property PACKAGE_PIN U14 [get_ports {LED_control[6]}]
set_property PACKAGE_PIN U15 [get_ports {LED_control[5]}]
set_property PACKAGE_PIN W18 [get_ports {LED_control[4]}]
set_property PACKAGE_PIN V19 [get_ports {LED_control[3]}]
set_property PACKAGE_PIN U19 [get_ports {LED_control[2]}]
set_property PACKAGE_PIN E19 [get_ports {LED_control[1]}]
set_property PACKAGE_PIN U16 [get_ports {LED_control[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {segs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segs[0]}]
set_property PACKAGE_PIN W7 [get_ports {segs[6]}]
set_property PACKAGE_PIN W6 [get_ports {segs[5]}]
set_property PACKAGE_PIN U8 [get_ports {segs[4]}]
set_property PACKAGE_PIN V8 [get_ports {segs[3]}]
set_property PACKAGE_PIN U5 [get_ports {segs[2]}]
set_property PACKAGE_PIN V5 [get_ports {segs[1]}]
set_property PACKAGE_PIN U7 [get_ports {segs[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd_ctl[0]}]
set_property PACKAGE_PIN W4 [get_ports {ssd_ctl[3]}]
set_property PACKAGE_PIN V4 [get_ports {ssd_ctl[2]}]
set_property PACKAGE_PIN U4 [get_ports {ssd_ctl[1]}]
set_property PACKAGE_PIN U2 [get_ports {ssd_ctl[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports point]
set_property PACKAGE_PIN V7 [get_ports point]

#input port
set_property IOSTANDARD LVCMOS33 [get_ports start_in]
set_property PACKAGE_PIN T17 [get_ports start_in]

set_property IOSTANDARD LVCMOS33 [get_ports pause_in]
set_property PACKAGE_PIN U17 [get_ports pause_in]

set_property IOSTANDARD LVCMOS33 [get_ports min_in]
set_property PACKAGE_PIN T18 [get_ports min_in]

set_property IOSTANDARD LVCMOS33 [get_ports hour_in]
set_property PACKAGE_PIN W19 [get_ports hour_in]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
set_property PACKAGE_PIN U18 [get_ports rst_in]

set_property IOSTANDARD LVCMOS33 [get_ports setting]
set_property PACKAGE_PIN V17 [get_ports setting]